#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun May 28 23:55:26 2017

@author: yuanzx
"""

import math
import numpy as np
import matplotlib.pyplot as plt

def TF2(w,t):
    return 16*w*w*t*t/(1+w*w*t*t)/(1+w*w*t*t)

def anoise(w,t):
    return (1+w)/(1+w)
    
def bnoise(w,t):
    return 1/w/w/t/t

w = np.arange(0.0, 12.0, 0.05)

plt.figure(1)
plt.plot(w, TF2(w,1),label=r"$16*|H(\omega)|^2, \tau = \tau_c$",color='red',lw=2)
plt.plot(w, TF2(w,2),label=r"$16*|H(\omega)|^2, \tau = 2\tau_c$",color='green',lw=2)
plt.plot(w,anoise(w,1),label="a noise PSD",color='blue',lw=3)
plt.plot(w,bnoise(w,1),label="b noise PSD",color="black",lw=3)

plt.legend(loc='best')
plt.xlabel(r"$\omega$",fontsize=18,fontweight='bold')
plt.ylabel("$Power$",fontsize=14,fontweight='bold')
plt.ylim(0,5)
plt.xlim(0,4)
plt.grid()
plt.savefig("CRRC_opt1.jpg",dpi=400)

plt.figure(2)
plt.plot(w, TF2(w,1),label=r"$16*|H(\omega\tau)|^2$",color='red',lw=2)
plt.plot(w,anoise(w,1),label="a noise PSD",color='blue',lw=3)
plt.plot(w,bnoise(w,1),label=r"b noise PSD,$\tau=\tau_c$",color="black",lw=3)
plt.plot(w,bnoise(w,1/2),label=r"b noise PSD,$\tau=2\tau_c$",color="green",lw=3)

plt.legend(loc='best')
plt.xlabel(r"$\omega \tau$",fontsize=18,fontweight='bold')
plt.ylabel("$Power$",fontsize=14,fontweight='bold')
plt.ylim(0,5)
plt.xlim(0,4)
plt.grid()
plt.savefig("CRRC_opt2.jpg",dpi=400)